### ISSUE TITLE
App hang during weibo sign in

### ISSUE THREAD

**Issue by mave99a** [pixomobile/pixotale-issues#607]
Got this error, and the app hang there sping forever. 

Sentry
New Event on Pixotale-production

URLError: <urlopen error [Errno 110] Connection timed out>
Tags

site = pixotale.com level = error logger = root server_name = ip-172-30-1-46 url = https://pixotale.com/api/v1/wblogin/
Exception

Stacktrace (most recent call last):

(10 additional frame(s) were not displayed)
...
  File "python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "python2.6/urllib2.py", line 1198, in https_open
    return self.do_open(httplib.HTTPSC!
 onnection, req)
  File "python2.6/urllib2.py", line 1165, in do_open
    raise URLError(err)
Request

URL https://pixotale.com/api/v1/wblogin/
Method  POST
Query   ''

**Comment by haitaoli** [comment]
Weibo request timed out. Added 15 second time out value on client
