### ISSUE TITLE
Comment view looks and feel need to be improved.

### ISSUE THREAD

**Issue by mave99a** [pixomobile/pixotale-issues#744]
Comment view looks and feel need to be improved. Should turn off a few elements since we don't allow those additional items for now.

**Comment by mave99a** [comment]
Need a parameter to turn off or config the "+" button and its items.

**Comment by jonathanlu813** [comment]
What's the current supported types? Photo, Location, URL, App Store? Also in terms of look and feel, do we want to change styles like fonts and colors to match Pixotale theme? The current style seems to fit CC more.

**Comment by mave99a** [comment]
Actually Pixotale now change to same fonts "OpenSans". 

The current supported type is text only. So in this case, the "+" need to be hidden. 

Ideally, we should pass in an array of supported input methods, (e.g. class? class name?) and anything get passed in will show up there.

**Comment by jonathanlu813** [comment]
resolved. ref: https://bitbucket.org/locql/sharedcodearc/commits/568d11ae716981ede2043fceda19f2161a831cf9
