### ISSUE TITLE
MessageView's empty cell / meta is not correct, it's now just load a normal message cell 

### ISSUE THREAD

**Issue by mave99a** [pixomobile/pixotale-issues#750]
MessageView's empty cell / meta is not correct, it's now just load a normal message cell. 

Easy to repo by simply few some comments, there is a dup.  (which is actually one of the message view cell) 

That was designed to load a cell to show some meta information: 
- Empty message view. (e.g. nothing there, so we should some message to encourage user write something) 
- Error (can't load anything, network error?)

**Comment by jonathanlu813** [comment]
This empty cell should only be shown when the message list is empty, or should be at the header of the list no matter what?

**Comment by mave99a** [comment]
Only when it's empty.

**Comment by jonathanlu813** [comment]
resolved. ref: https://bitbucket.org/locql/sharedcodearc/commits/1056ce02ee7217b40501179d3bdb23b5e333274d
